### ISSUE TITLE
Feature request: Add option to show bar only on hover

### ISSUE THREAD

**Issue by Abdullah16M** [63BeetleSmurf/PinnyNotes#13]
This bar:
![image](https://github.com/user-attachments/assets/66b6d7e4-9f18-45d9-8965-3520593a7cbb)

Thanks for the application

**Comment by 63BeetleSmurf** [comment]
https://github.com/63BeetleSmurf/PinnyNotes/commit/51ca697a6e53d3719335b69ae09860ac7402f23d
