### ISSUE TITLE
Feature request: Allow resizing to content height

### ISSUE THREAD

**Issue by Abdullah16M** [63BeetleSmurf/PinnyNotes#15]
Example:
![image](https://github.com/user-attachments/assets/de7dcd24-0c2a-4a64-a929-a671265fdf0e)

I usually use sticky notes to focus on tasks or pin some info i need to work on, usually those don't occupy much space.

![image](https://github.com/user-attachments/assets/4fb6ae63-9a0c-419e-a295-7fa7363cb384)

**Comment by 63BeetleSmurf** [comment]
https://github.com/63BeetleSmurf/PinnyNotes/commit/43d246a47d4d680fa29bb5de869ff320e6ac8824
