### ISSUE TITLE
Yellow note bug

### ISSUE THREAD

**Issue by mathieucloutier86** [63BeetleSmurf/PinnyNotes#17]
When the cycling of colors is disabled and yellow is chosen as the default color, I observe that creating a new note will add a  note in the taskbar, but the note will not appear anywhere on the display. I've been observing this on multiple machines, under both operating under W10 and W11, during a timeframe of over two months.

Thanks,
Mathieu

**Comment by 63BeetleSmurf** [comment]
Hi Mathieu,

Thanks for letting me know about that one, I've put out a new release with the bug fixed: https://github.com/63BeetleSmurf/PinnyNotes/releases/tag/v1.11.3

https://github.com/63BeetleSmurf/PinnyNotes/commit/29f1a824b4b730cfc37c20d1209b2d43042ff7a4 - Issues was due to yellow being the default value meaning it didn't trigger the value changed method which applies the theme.

**Comment by mathieucloutier86** [comment]
Hello !

My pleasure. I confirm it is now working as expected.

Just a quick question : Would you consider having an autosave option for
the notes ? I know we can saves them to text files, but I wouldn't intend
to do that as they are only temporary notes. In case of BSOD however, it
would be great to know that the content of the stickies will automatically
be displayed when the app is launched again. ( Sorry for not login in and
ask it in a new request, I'm currently logged out of Github. )

What do you think?
Best,
Mathieu

**Comment by mathieucloutier86** [comment]
Hi !

That's good to hear ! Years before discovering your project,  I've used
something called PNotes : https://pnotes-1932d.firebaseapp.com/home

Maybe you can draw some ideas or code from it. I really do appreciate the
simplicity of Pinny Notes though : more elaborate note taking should not
take place on stickies anyways, there are apps such as Simplenote, Joplin
or Obsidian for this.

I'm not a programmer, but I'll do my best to contribute in any way I can.
Just let me know if you need something.

Thanks again,
Mathieu

**Comment by 63BeetleSmurf** [comment]
Hi Mathieu,

PNotes looks good and I'll certainly have a look though it's features for any inspiration, but yes it is more elaborate than where I see Pinny Notes going. I like simple, quick and clean notes, e.g. the management window will be more like the one found in https://github.com/linuxmint/sticky with just a list of your groups and the notes in them.

Thanks, just keep giving feedback and tell others who may like it. That would be much appreciated and will hopefully keep the project moving.
